//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/sources/evobasic-project-antlr/ebc\evoBasic.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IevoBasicListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class evoBasicBaseListener : IevoBasicListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] evoBasicParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] evoBasicParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] evoBasicParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] evoBasicParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.declarationNoAccessFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationNoAccessFlag([NotNull] evoBasicParser.DeclarationNoAccessFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.declarationNoAccessFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationNoAccessFlag([NotNull] evoBasicParser.DeclarationNoAccessFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.ctorDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtorDecl([NotNull] evoBasicParser.CtorDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.ctorDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtorDecl([NotNull] evoBasicParser.CtorDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.extendPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtendPart([NotNull] evoBasicParser.ExtendPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.extendPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtendPart([NotNull] evoBasicParser.ExtendPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDecl([NotNull] evoBasicParser.ClassDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.classDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDecl([NotNull] evoBasicParser.ClassDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.implPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplPart([NotNull] evoBasicParser.ImplPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.implPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplPart([NotNull] evoBasicParser.ImplPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.moduleDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModuleDecl([NotNull] evoBasicParser.ModuleDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.moduleDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModuleDecl([NotNull] evoBasicParser.ModuleDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.dimDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimDecl([NotNull] evoBasicParser.DimDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.dimDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimDecl([NotNull] evoBasicParser.DimDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDecl([NotNull] evoBasicParser.TypeDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.typeDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDecl([NotNull] evoBasicParser.TypeDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.enumDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDecl([NotNull] evoBasicParser.EnumDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.enumDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDecl([NotNull] evoBasicParser.EnumDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumConstant([NotNull] evoBasicParser.EnumConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.enumConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumConstant([NotNull] evoBasicParser.EnumConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.externalFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalFunc([NotNull] evoBasicParser.ExternalFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.externalFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalFunc([NotNull] evoBasicParser.ExternalFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.externalSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalSub([NotNull] evoBasicParser.ExternalSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.externalSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalSub([NotNull] evoBasicParser.ExternalSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.importDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImportDecl([NotNull] evoBasicParser.ImportDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.importDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImportDecl([NotNull] evoBasicParser.ImportDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDecl([NotNull] evoBasicParser.FunctionDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.functionDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDecl([NotNull] evoBasicParser.FunctionDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.subDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubDecl([NotNull] evoBasicParser.SubDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.subDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubDecl([NotNull] evoBasicParser.SubDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] evoBasicParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] evoBasicParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] evoBasicParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] evoBasicParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.accessFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessFlag([NotNull] evoBasicParser.AccessFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.accessFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessFlag([NotNull] evoBasicParser.AccessFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.methodFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodFlag([NotNull] evoBasicParser.MethodFlagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.methodFlag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodFlag([NotNull] evoBasicParser.MethodFlagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] evoBasicParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] evoBasicParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.throwStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThrowStmt([NotNull] evoBasicParser.ThrowStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.throwStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThrowStmt([NotNull] evoBasicParser.ThrowStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.tryStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTryStmt([NotNull] evoBasicParser.TryStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.tryStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTryStmt([NotNull] evoBasicParser.TryStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.catchPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCatchPart([NotNull] evoBasicParser.CatchPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.catchPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCatchPart([NotNull] evoBasicParser.CatchPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStmt([NotNull] evoBasicParser.ForStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.forStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStmt([NotNull] evoBasicParser.ForStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.forIterator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForIterator([NotNull] evoBasicParser.ForIteratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.forIterator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForIterator([NotNull] evoBasicParser.ForIteratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.dimStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimStmt([NotNull] evoBasicParser.DimStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.dimStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimStmt([NotNull] evoBasicParser.DimStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.variableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDecl([NotNull] evoBasicParser.VariableDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.variableDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDecl([NotNull] evoBasicParser.VariableDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.loopStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStmt([NotNull] evoBasicParser.LoopStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.loopStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStmt([NotNull] evoBasicParser.LoopStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.onelineIfStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnelineIfStmt([NotNull] evoBasicParser.OnelineIfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.onelineIfStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnelineIfStmt([NotNull] evoBasicParser.OnelineIfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStmt([NotNull] evoBasicParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStmt([NotNull] evoBasicParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.elseIfPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfPart([NotNull] evoBasicParser.ElseIfPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.elseIfPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfPart([NotNull] evoBasicParser.ElseIfPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.elsePart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElsePart([NotNull] evoBasicParser.ElsePartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.elsePart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElsePart([NotNull] evoBasicParser.ElsePartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.selectStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectStmt([NotNull] evoBasicParser.SelectStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.selectStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectStmt([NotNull] evoBasicParser.SelectStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.caseList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseList([NotNull] evoBasicParser.CaseListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.caseList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseList([NotNull] evoBasicParser.CaseListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.controlStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterControlStmt([NotNull] evoBasicParser.ControlStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.controlStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitControlStmt([NotNull] evoBasicParser.ControlStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStmt([NotNull] evoBasicParser.ExprStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.exprStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStmt([NotNull] evoBasicParser.ExprStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] evoBasicParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] evoBasicParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] evoBasicParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] evoBasicParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] evoBasicParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] evoBasicParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalExpression([NotNull] evoBasicParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalExpression([NotNull] evoBasicParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.conditionalNotExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalNotExpression([NotNull] evoBasicParser.ConditionalNotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.conditionalNotExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalNotExpression([NotNull] evoBasicParser.ConditionalNotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] evoBasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] evoBasicParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.relationalOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalOp([NotNull] evoBasicParser.RelationalOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.relationalOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalOp([NotNull] evoBasicParser.RelationalOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] evoBasicParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] evoBasicParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] evoBasicParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] evoBasicParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] evoBasicParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] evoBasicParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryTerminal</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryTerminal([NotNull] evoBasicParser.PrimaryTerminalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryTerminal</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryTerminal([NotNull] evoBasicParser.PrimaryTerminalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArraySubscription</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArraySubscription([NotNull] evoBasicParser.ArraySubscriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArraySubscription</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArraySubscription([NotNull] evoBasicParser.ArraySubscriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DotExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotExpression([NotNull] evoBasicParser.DotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DotExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotExpression([NotNull] evoBasicParser.DotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IsExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsExpression([NotNull] evoBasicParser.IsExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IsExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsExpression([NotNull] evoBasicParser.IsExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionalTestExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptionalTestExpression([NotNull] evoBasicParser.OptionalTestExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionalTestExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptionalTestExpression([NotNull] evoBasicParser.OptionalTestExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewExpression([NotNull] evoBasicParser.NewExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewExpression([NotNull] evoBasicParser.NewExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodInvocation([NotNull] evoBasicParser.MethodInvocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodInvocation([NotNull] evoBasicParser.MethodInvocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCastExpression([NotNull] evoBasicParser.CastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCastExpression([NotNull] evoBasicParser.CastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.typePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypePath([NotNull] evoBasicParser.TypePathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.typePath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypePath([NotNull] evoBasicParser.TypePathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.terminalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminalExpression([NotNull] evoBasicParser.TerminalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.terminalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminalExpression([NotNull] evoBasicParser.TerminalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntegerLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] evoBasicParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntegerLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] evoBasicParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoubleLiteral([NotNull] evoBasicParser.DoubleLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoubleLiteral([NotNull] evoBasicParser.DoubleLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] evoBasicParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] evoBasicParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RuneLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuneLiteral([NotNull] evoBasicParser.RuneLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RuneLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuneLiteral([NotNull] evoBasicParser.RuneLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BooleanLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] evoBasicParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BooleanLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] evoBasicParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayLiteral([NotNull] evoBasicParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayLiteral([NotNull] evoBasicParser.ArrayLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NothingLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNothingLiteral([NotNull] evoBasicParser.NothingLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NothingLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNothingLiteral([NotNull] evoBasicParser.NothingLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.ltOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLtOp([NotNull] evoBasicParser.LtOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.ltOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLtOp([NotNull] evoBasicParser.LtOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.leOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeOp([NotNull] evoBasicParser.LeOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.leOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeOp([NotNull] evoBasicParser.LeOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.eqOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqOp([NotNull] evoBasicParser.EqOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.eqOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqOp([NotNull] evoBasicParser.EqOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.geOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeOp([NotNull] evoBasicParser.GeOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.geOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeOp([NotNull] evoBasicParser.GeOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.gtOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGtOp([NotNull] evoBasicParser.GtOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.gtOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGtOp([NotNull] evoBasicParser.GtOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.neOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNeOp([NotNull] evoBasicParser.NeOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.neOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNeOp([NotNull] evoBasicParser.NeOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.divOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivOp([NotNull] evoBasicParser.DivOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.divOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivOp([NotNull] evoBasicParser.DivOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.mulOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulOp([NotNull] evoBasicParser.MulOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.mulOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulOp([NotNull] evoBasicParser.MulOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.plusOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlusOp([NotNull] evoBasicParser.PlusOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.plusOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlusOp([NotNull] evoBasicParser.PlusOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.minusOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMinusOp([NotNull] evoBasicParser.MinusOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.minusOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMinusOp([NotNull] evoBasicParser.MinusOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] evoBasicParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] evoBasicParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] evoBasicParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] evoBasicParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] evoBasicParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] evoBasicParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.subScriptSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubScriptSuffix([NotNull] evoBasicParser.SubScriptSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.subScriptSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubScriptSuffix([NotNull] evoBasicParser.SubScriptSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.newline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewline([NotNull] evoBasicParser.NewlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.newline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewline([NotNull] evoBasicParser.NewlineContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
