//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/sources/evobasic-project-antlr/ebc\evoBasic.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="evoBasicParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IevoBasicListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] evoBasicParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] evoBasicParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] evoBasicParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] evoBasicParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.declarationNoAccessFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationNoAccessFlag([NotNull] evoBasicParser.DeclarationNoAccessFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.declarationNoAccessFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationNoAccessFlag([NotNull] evoBasicParser.DeclarationNoAccessFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.ctorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtorDecl([NotNull] evoBasicParser.CtorDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.ctorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtorDecl([NotNull] evoBasicParser.CtorDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.extendPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendPart([NotNull] evoBasicParser.ExtendPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.extendPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendPart([NotNull] evoBasicParser.ExtendPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDecl([NotNull] evoBasicParser.ClassDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.classDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDecl([NotNull] evoBasicParser.ClassDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.implPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplPart([NotNull] evoBasicParser.ImplPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.implPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplPart([NotNull] evoBasicParser.ImplPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.moduleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleDecl([NotNull] evoBasicParser.ModuleDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.moduleDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleDecl([NotNull] evoBasicParser.ModuleDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.dimDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimDecl([NotNull] evoBasicParser.DimDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.dimDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimDecl([NotNull] evoBasicParser.DimDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDecl([NotNull] evoBasicParser.TypeDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.typeDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDecl([NotNull] evoBasicParser.TypeDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDecl([NotNull] evoBasicParser.EnumDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.enumDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDecl([NotNull] evoBasicParser.EnumDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumConstant([NotNull] evoBasicParser.EnumConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.enumConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumConstant([NotNull] evoBasicParser.EnumConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.externalFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalFunc([NotNull] evoBasicParser.ExternalFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.externalFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalFunc([NotNull] evoBasicParser.ExternalFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.externalSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalSub([NotNull] evoBasicParser.ExternalSubContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.externalSub"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalSub([NotNull] evoBasicParser.ExternalSubContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.importDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportDecl([NotNull] evoBasicParser.ImportDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.importDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportDecl([NotNull] evoBasicParser.ImportDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] evoBasicParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] evoBasicParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.subDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubDecl([NotNull] evoBasicParser.SubDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.subDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubDecl([NotNull] evoBasicParser.SubDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] evoBasicParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] evoBasicParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] evoBasicParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] evoBasicParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.accessFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessFlag([NotNull] evoBasicParser.AccessFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.accessFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessFlag([NotNull] evoBasicParser.AccessFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.methodFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodFlag([NotNull] evoBasicParser.MethodFlagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.methodFlag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodFlag([NotNull] evoBasicParser.MethodFlagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] evoBasicParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] evoBasicParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.throwStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowStmt([NotNull] evoBasicParser.ThrowStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.throwStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowStmt([NotNull] evoBasicParser.ThrowStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.tryStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryStmt([NotNull] evoBasicParser.TryStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.tryStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryStmt([NotNull] evoBasicParser.TryStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.catchPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatchPart([NotNull] evoBasicParser.CatchPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.catchPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatchPart([NotNull] evoBasicParser.CatchPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStmt([NotNull] evoBasicParser.ForStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.forStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStmt([NotNull] evoBasicParser.ForStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.forIterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForIterator([NotNull] evoBasicParser.ForIteratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.forIterator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForIterator([NotNull] evoBasicParser.ForIteratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.dimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimStmt([NotNull] evoBasicParser.DimStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.dimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimStmt([NotNull] evoBasicParser.DimStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.variableDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDecl([NotNull] evoBasicParser.VariableDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.variableDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDecl([NotNull] evoBasicParser.VariableDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.loopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopStmt([NotNull] evoBasicParser.LoopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.loopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopStmt([NotNull] evoBasicParser.LoopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.onelineIfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnelineIfStmt([NotNull] evoBasicParser.OnelineIfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.onelineIfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnelineIfStmt([NotNull] evoBasicParser.OnelineIfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStmt([NotNull] evoBasicParser.IfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.ifStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStmt([NotNull] evoBasicParser.IfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.elseIfPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfPart([NotNull] evoBasicParser.ElseIfPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.elseIfPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfPart([NotNull] evoBasicParser.ElseIfPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.elsePart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElsePart([NotNull] evoBasicParser.ElsePartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.elsePart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElsePart([NotNull] evoBasicParser.ElsePartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.selectStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectStmt([NotNull] evoBasicParser.SelectStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.selectStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectStmt([NotNull] evoBasicParser.SelectStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.caseList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseList([NotNull] evoBasicParser.CaseListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.caseList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseList([NotNull] evoBasicParser.CaseListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.controlStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStmt([NotNull] evoBasicParser.ControlStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.controlStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStmt([NotNull] evoBasicParser.ControlStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStmt([NotNull] evoBasicParser.ExprStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.exprStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStmt([NotNull] evoBasicParser.ExprStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] evoBasicParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] evoBasicParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] evoBasicParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] evoBasicParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] evoBasicParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] evoBasicParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] evoBasicParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] evoBasicParser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.conditionalNotExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalNotExpression([NotNull] evoBasicParser.ConditionalNotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.conditionalNotExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalNotExpression([NotNull] evoBasicParser.ConditionalNotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] evoBasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] evoBasicParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.relationalOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalOp([NotNull] evoBasicParser.RelationalOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.relationalOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalOp([NotNull] evoBasicParser.RelationalOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] evoBasicParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] evoBasicParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] evoBasicParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] evoBasicParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] evoBasicParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] evoBasicParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrimaryTerminal</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryTerminal([NotNull] evoBasicParser.PrimaryTerminalContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrimaryTerminal</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryTerminal([NotNull] evoBasicParser.PrimaryTerminalContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArraySubscription</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArraySubscription([NotNull] evoBasicParser.ArraySubscriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArraySubscription</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArraySubscription([NotNull] evoBasicParser.ArraySubscriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DotExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotExpression([NotNull] evoBasicParser.DotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DotExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotExpression([NotNull] evoBasicParser.DotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IsExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsExpression([NotNull] evoBasicParser.IsExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IsExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsExpression([NotNull] evoBasicParser.IsExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>OptionalTestExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionalTestExpression([NotNull] evoBasicParser.OptionalTestExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>OptionalTestExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionalTestExpression([NotNull] evoBasicParser.OptionalTestExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewExpression([NotNull] evoBasicParser.NewExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NewExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewExpression([NotNull] evoBasicParser.NewExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodInvocation([NotNull] evoBasicParser.MethodInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MethodInvocation</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodInvocation([NotNull] evoBasicParser.MethodInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] evoBasicParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CastExpression</c>
	/// labeled alternative in <see cref="evoBasicParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] evoBasicParser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.typePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypePath([NotNull] evoBasicParser.TypePathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.typePath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypePath([NotNull] evoBasicParser.TypePathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.terminalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminalExpression([NotNull] evoBasicParser.TerminalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.terminalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminalExpression([NotNull] evoBasicParser.TerminalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntegerLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerLiteral([NotNull] evoBasicParser.IntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntegerLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerLiteral([NotNull] evoBasicParser.IntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoubleLiteral([NotNull] evoBasicParser.DoubleLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DoubleLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoubleLiteral([NotNull] evoBasicParser.DoubleLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] evoBasicParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StringLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] evoBasicParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RuneLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuneLiteral([NotNull] evoBasicParser.RuneLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RuneLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuneLiteral([NotNull] evoBasicParser.RuneLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BooleanLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanLiteral([NotNull] evoBasicParser.BooleanLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BooleanLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanLiteral([NotNull] evoBasicParser.BooleanLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayLiteral([NotNull] evoBasicParser.ArrayLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayLiteral([NotNull] evoBasicParser.ArrayLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NothingLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNothingLiteral([NotNull] evoBasicParser.NothingLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NothingLiteral</c>
	/// labeled alternative in <see cref="evoBasicParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNothingLiteral([NotNull] evoBasicParser.NothingLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.ltOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLtOp([NotNull] evoBasicParser.LtOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.ltOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLtOp([NotNull] evoBasicParser.LtOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.leOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeOp([NotNull] evoBasicParser.LeOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.leOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeOp([NotNull] evoBasicParser.LeOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.eqOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqOp([NotNull] evoBasicParser.EqOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.eqOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqOp([NotNull] evoBasicParser.EqOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.geOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeOp([NotNull] evoBasicParser.GeOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.geOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeOp([NotNull] evoBasicParser.GeOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.gtOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGtOp([NotNull] evoBasicParser.GtOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.gtOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGtOp([NotNull] evoBasicParser.GtOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.neOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNeOp([NotNull] evoBasicParser.NeOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.neOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNeOp([NotNull] evoBasicParser.NeOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.divOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivOp([NotNull] evoBasicParser.DivOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.divOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivOp([NotNull] evoBasicParser.DivOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulOp([NotNull] evoBasicParser.MulOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.mulOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulOp([NotNull] evoBasicParser.MulOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.plusOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlusOp([NotNull] evoBasicParser.PlusOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.plusOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlusOp([NotNull] evoBasicParser.PlusOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.minusOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMinusOp([NotNull] evoBasicParser.MinusOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.minusOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMinusOp([NotNull] evoBasicParser.MinusOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] evoBasicParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] evoBasicParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] evoBasicParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] evoBasicParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] evoBasicParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] evoBasicParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.subScriptSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubScriptSuffix([NotNull] evoBasicParser.SubScriptSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.subScriptSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubScriptSuffix([NotNull] evoBasicParser.SubScriptSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="evoBasicParser.newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewline([NotNull] evoBasicParser.NewlineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="evoBasicParser.newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewline([NotNull] evoBasicParser.NewlineContext context);
}
